CREATE TABLE IF NOT EXISTS cart_header (
       user_id BIGINT UNSIGNED NOT NULL,
       merchant_id BIGINT UNSIGNED DEFAULT NULL,
       PRIMARY KEY (user_id)
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_0900_ai_ci;